// <auto-generated />
using System;
using Microservice.Register.Function.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Microservice.Register.Function.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microservice.Register.Function.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("VerificationToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Verified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MSOS_User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa1dc96f-3be5-41cd-8a1b-207284af3fdd"),
                            Created = new DateTime(2023, 8, 18, 15, 21, 38, 875, DateTimeKind.Unspecified).AddTicks(7677),
                            Email = "corday10@hotmail.com",
                            LastUpdated = new DateTime(2024, 3, 20, 18, 6, 46, 238, DateTimeKind.Local).AddTicks(606),
                            PasswordHash = "$2a$11$sUclSCnqTUlmXReP68uXxuqlf1TW0RjG9lovnv21/Z6R4BYoH7XeC",
                            Role = 3,
                            VerificationToken = "lGoeUM53kxNLZlkznM4rpDjWTJa9rNcyjCAKonHeeX08TtM0C8wpbQ44",
                            Verified = new DateTime(2023, 8, 18, 15, 21, 38, 875, DateTimeKind.Unspecified).AddTicks(8226)
                        },
                        new
                        {
                            Id = new Guid("af95fb7e-8d97-4892-8da3-5e6e51c54044"),
                            Created = new DateTime(2023, 8, 18, 15, 26, 46, 292, DateTimeKind.Unspecified).AddTicks(9450),
                            Email = "corday11@hotmail.com",
                            LastUpdated = new DateTime(2024, 3, 20, 18, 6, 46, 238, DateTimeKind.Local).AddTicks(630),
                            PasswordHash = "$2a$11$NWAxlt6tssER3IVzNA7Xw.b.ZCim3T3z58JDz/ilPmz/JhHutjDkS",
                            Role = 3,
                            VerificationToken = "5rGMUNyYN85wyB9o7Hn2ylEIo8w3Tlt3LtB8cSm4ks6wfF0TiMz9eQ44",
                            Verified = new DateTime(2023, 8, 18, 15, 26, 46, 293, DateTimeKind.Unspecified).AddTicks(65)
                        },
                        new
                        {
                            Id = new Guid("55b431ff-693e-4664-8f65-cfd8d0b14b1b"),
                            Created = new DateTime(2023, 8, 18, 15, 30, 59, 231, DateTimeKind.Unspecified).AddTicks(9879),
                            Email = "corday12@hotmail.com",
                            LastUpdated = new DateTime(2024, 3, 20, 18, 6, 46, 238, DateTimeKind.Local).AddTicks(642),
                            PasswordHash = "$2a$11$R26bWvkESNmNSeLOcpNDOebwu2vUQP6RaOCB18ujskdd/Gctpzy3m",
                            Role = 3,
                            VerificationToken = "JikIR425mjxRk2vRKHdYgYfscjsMx-nPqs8xzk5V99420MxFFXQDdg44",
                            Verified = new DateTime(2023, 8, 18, 15, 30, 59, 232, DateTimeKind.Unspecified).AddTicks(1080)
                        },
                        new
                        {
                            Id = new Guid("2385de72-2302-4ced-866a-fa199116ca6e"),
                            Created = new DateTime(2023, 8, 18, 15, 40, 30, 801, DateTimeKind.Unspecified).AddTicks(3615),
                            Email = "corday13@hotmail.com",
                            LastUpdated = new DateTime(2024, 3, 20, 18, 6, 46, 238, DateTimeKind.Local).AddTicks(654),
                            PasswordHash = "$2a$11$/k9/nqKpHgXlr6CTMVoZbu8HBLCebf1NdrP71LcgQWrVmFl/FP7.S",
                            Role = 3,
                            VerificationToken = "NYCscmP1Q3z76pQY_Y01Cdqwe_khc_YpwxkLwqGukgrMVDOEBitxQg44",
                            Verified = new DateTime(2023, 8, 18, 15, 40, 30, 801, DateTimeKind.Unspecified).AddTicks(4311)
                        },
                        new
                        {
                            Id = new Guid("47417642-87d9-4047-ae13-4c721d99ab48"),
                            Created = new DateTime(2023, 8, 18, 15, 42, 7, 633, DateTimeKind.Unspecified).AddTicks(1653),
                            Email = "corday14@hotmail.com",
                            LastUpdated = new DateTime(2024, 3, 20, 18, 6, 46, 238, DateTimeKind.Local).AddTicks(666),
                            PasswordHash = "$2a$11$wdkVIkHA1Cr0EZeE3Jk1seCSl5OT/hDlXjR6LpSY3XItN7F/gQp4S",
                            Role = 3,
                            VerificationToken = "d4fWNZNRF98DltZ3SKo3ggp2N-P3lG-1LOUiyv2mfPprdCJFxtZXdQ44",
                            Verified = new DateTime(2023, 8, 18, 15, 42, 7, 633, DateTimeKind.Unspecified).AddTicks(2373)
                        },
                        new
                        {
                            Id = new Guid("ff4d5a80-81e3-42e3-8052-92cf5c51e797"),
                            Created = new DateTime(2023, 8, 18, 15, 45, 55, 760, DateTimeKind.Unspecified).AddTicks(1533),
                            Email = "corday15@hotmail.com",
                            LastUpdated = new DateTime(2024, 3, 20, 18, 6, 46, 238, DateTimeKind.Local).AddTicks(681),
                            PasswordHash = "$2a$11$H8BS6j19gUmelCX7F1pUeul0.27ARe7H9Ux3O9s.LBOfXyPgKGLDi",
                            Role = 3,
                            VerificationToken = "TC9IVqrD-n6nWkfJH0i4OT8rHM7g8xo08WrnWfAehrRy8xSgG_zgRQ44",
                            Verified = new DateTime(2023, 8, 18, 15, 45, 55, 760, DateTimeKind.Unspecified).AddTicks(2347)
                        },
                        new
                        {
                            Id = new Guid("5ff79dfe-c1fa-4dd9-996f-bc96649d6dfc"),
                            Created = new DateTime(2023, 8, 18, 15, 48, 31, 270, DateTimeKind.Unspecified).AddTicks(6793),
                            Email = "corday16@hotmail.com",
                            LastUpdated = new DateTime(2024, 3, 20, 18, 6, 46, 238, DateTimeKind.Local).AddTicks(692),
                            PasswordHash = "$2a$11$op7y2GsDxvl7cZqqRrBpRuNf85luc.bVdWqRGSkh9XWbPnKNO9dXm",
                            Role = 3,
                            VerificationToken = "l-K_Il3aA25ZDAETMzhfqXMflCE0C_8vfG20pNd0isnTomQ1YN2fpw44",
                            Verified = new DateTime(2023, 8, 18, 15, 48, 31, 270, DateTimeKind.Unspecified).AddTicks(7367)
                        },
                        new
                        {
                            Id = new Guid("ae55b0d1-ba02-41e1-9efa-9b4d4ac15eec"),
                            Created = new DateTime(2023, 8, 18, 15, 53, 1, 715, DateTimeKind.Unspecified).AddTicks(4228),
                            Email = "corday17@hotmail.com",
                            LastUpdated = new DateTime(2024, 3, 20, 18, 6, 46, 238, DateTimeKind.Local).AddTicks(704),
                            PasswordHash = "$2a$11$kbeO4QR4kdl/uxLRSmGdJOSEs2PRNQFFPKFxthqICX0maXxEfNZ5C",
                            Role = 3,
                            VerificationToken = "mEId4vbifX3S5LfPd0eEhQ7BgNs6xz6cDwLPTBuPuwc6OFf8Yw2hBw44",
                            Verified = new DateTime(2023, 8, 18, 15, 53, 1, 715, DateTimeKind.Unspecified).AddTicks(4754)
                        },
                        new
                        {
                            Id = new Guid("c95ba8ff-06a1-49d0-bc45-83f89b3ce820"),
                            Created = new DateTime(2023, 8, 18, 15, 55, 44, 946, DateTimeKind.Unspecified).AddTicks(2678),
                            Email = "corday18@hotmail.com",
                            LastUpdated = new DateTime(2024, 3, 20, 18, 6, 46, 238, DateTimeKind.Local).AddTicks(715),
                            PasswordHash = "$2a$11$jBIzZuggUZu52NOWAjlv6e2rVpIARa87JqSxdKUOe1RZ2KVZdSmDa",
                            Role = 3,
                            VerificationToken = "B8eXsXrt4NqdYwjiJWpVYVUGPdnetlF-Gt8pbBJvqjp8hH6CsentXQ44",
                            Verified = new DateTime(2023, 8, 18, 15, 55, 44, 946, DateTimeKind.Unspecified).AddTicks(3214)
                        },
                        new
                        {
                            Id = new Guid("f07e88ac-53b2-4def-af07-957cbb18523c"),
                            Created = new DateTime(2023, 8, 18, 16, 3, 37, 86, DateTimeKind.Unspecified).AddTicks(5647),
                            Email = "corday19@hotmail.com",
                            LastUpdated = new DateTime(2024, 3, 20, 18, 6, 46, 238, DateTimeKind.Local).AddTicks(728),
                            PasswordHash = "$2a$11$7Gb7oXNl0fMzRK3S6.2s1OUJ5tPTvlG44MgyIiguYZCsOYFCS98de",
                            Role = 3,
                            VerificationToken = "FwqSTqfEtdJanlaWArkYn5M4YH9lAHWBVq3HHtqK-Htw5pUlPy7R4w44",
                            Verified = new DateTime(2023, 8, 18, 16, 3, 37, 86, DateTimeKind.Unspecified).AddTicks(6301)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
